---
title: "Warm Up"
subtitle: "Andrew Dickinson"
date: last-modified
self-contained: TRUE
format:
  html:
    theme: 
      - cosmo
      - doc-styles.scss
    toc: true
    toc-depth: 3
    html-math-method: mathjax
    number-sections: false
---

[Q01.]{.question} Explain the concept of a sampling distribution on an estimator. What 

::: {.answer style="display: inherit;"}

The sampling distribution of an estimator is the distribution of the estimator's values over many samples. In other words, the sampling distribution is the distribution of the estimates that would be obtained if the estimator were calculated for many different samples of the same size from the same population.

:::

[Q02.]{.question} What are two criteria of a a good estimator? Describe each in your own words and explain how we can visualize them in a sampling distribution.

::: {.answer style="display: inherit;"}

- **Unbiasedness**: An estimator is unbiased if the expected value of the estimator is equal to the true value of the parameter being estimated. In other words, the estimator is unbiased if the average of the estimates is equal to the true value of the parameter. The sampling distribution of an unbiased estimator is centered around the true value of the parameter being estimated.

- **Efficiency**: An estimator is efficient if it has the smallest variance of all unbiased estimators. In other words, the estimator is efficient if it is the most precise estimator among all unbiased estimators. The sampling distribution of an efficient estimator has the smallest spread around the true value of the parameter being estimated.

:::

